### PR TITLE
fix eval of featureGraphic, add dev email+website

### PR DESCRIPTION
**Pull request by IzzySoft**
Finally got rid of that rarely working loop and now reliably obtaining featureGraphic (plus adding developerEmail and developerWebsite). As the loop was dropped, this also gives a nice performance boost :smile:

Ready to go, @BaseMax – just take a look if you wish and merge if you agree :smiley:

### CODE REVIEW

**Review by BaseMax — APPROVED** [review]
Nice. developerEmail and developerWebsite are good to have.

**Comment by BaseMax** [comment]
```
    while ( empty($proto) && $limit > 0 ) { // sometimes protobuf is missing, but present again on subsequent call
```

Are you sure we not need the while/loop anymore?

**Comment by IzzySoft** [comment]
PS: Do you think with this merged, another release should be made? If so, what version would you suggest? I'd go with v1.2.0 if you agree. Last release was almost a year ago, and there were quite some fixes/improvements applied since.

**Comment by BaseMax** [comment]
`v1.2.0` is fine.

**Comment by BaseMax** [comment]
Before going to release, README, Documentation and wiki need to be updated.

**Comment by IzzySoft** [comment]
> Are you sure we not need the while/loop anymore?

I'm running without that for about a week now, so: yes, pretty sure. You might have noticed those data are now taken from a different `ds` (DataSet). Either they were "shuffled around" (which I assume, as while featureGraphic worked in the past it entirely stopped working months ago) – or we were looking at the wrong spot all the time. So TL;DR: that loop just went to its max count for nothing since then.

> Before going to release, README, Documentation and wiki need to be updated.

I already had updating the wiki with those two new fields on my todo for once this MR got merged. Will do that now; would you take care for the other spots (or at least point out what specifically should be added/changed/updated)?

**Comment by IzzySoft** [comment]
Urgs. Looks like reviews are broken now, `ds:7` only has empty values. (looking around) haha, they've moved to `ds:8`. Which confirms my above suspicion that Google moves things around there. Let me see if changing to `ds:8` solves that issue. If so, expect another MR before the release.

**Edit:** yes, it does. MR coming once I've updated the rest. Who knows what else might pop up.

**Comment by IzzySoft** [comment]
OK, fixed – and the wiki page on AppDetails updated. Give me a ping when I shall tag and release, I'll then write up the release notes as well.

**Comment by IzzySoft** [comment]
OK, maybe I was a little impatient – but I hope I got all the places that needed a little updating. Release is tagged and pushed now.

**Comment by IzzySoft** [comment]
PS: Would you mind changing the merge strategy default to "rebase & merge" (instead of "merge commit") for a cleaner history, @BaseMax? That would avoid the extra merge commit. I can't do that myself as I cannot access the project's settings.

**Pull request merged**
