### PR TITLE
minor fix-ups

### PR DESCRIPTION
**Pull request by IzzySoft**
Feel free to merge and then to cleanup the ReadMe after having investigated the new Wiki pages. I won't have much time tomorrow (having a full-time event to host). If something's amiss, just let me know.

One question still unanswered is whether `parseApplication()` should filter out the English description when it was left in despite of the language-specific one being present (but "hidden"). The separator in such cases seems to be static, as far as I have seen up to now. Shouldn't be too hard to do – I just didn't want to decide that "over your head". My suggestion is we should do that.

We could bind it to the `$debug` property (e.g. always clean the comment *unless*  debug is set), at least for a while, to have an easy way to cross-check on empty descriptions (in case the replace "overdid" it). For that, I'd also suggest adding a getter/setter like `setDebug(bool)`, so users could trigger it if they wish to test – without modifying the class file.

Be welcome to open a ticket and assign it to me if you agree.

### CODE REVIEW

**Review by BaseMax — APPROVED** [review]
Thanks.

**Comment by BaseMax** [comment]
> having a full-time event to host

Tell me if I can help you.

Yes, today and tomorrow GitHub has a global event which is a busy day.

**Comment by BaseMax** [comment]
> Be welcome to open a ticket and assign it to me if you agree.

Create issue then PR...
Agree, thank you whenever you can send this for a closer look.

**Comment by IzzySoft** [comment]
> Yes, today and tomorrow GitHub has a global event which is a busy day.

Oh? On my end it was an Oracle training course I had to give. Must make a living from something, too :wink:

> Create issue then PR...

You want both?

**Pull request merged**
