### PR TITLE
list similar apps, move ReadMe content to wiki

### PR DESCRIPTION
**Pull request by IzzySoft**
* new method `parseSimilar()` lists what Google considers "similar apps"
* removed content from ReadMe that has been moved to wiki
* added links to ReadMe on what can be found on which wiki page
* added short description on method listing to ReadMe

Wiki update for the new method on its way. Ready for merge at your convenience.

### CODE REVIEW

**Comment by BaseMax** [comment]
Ready for review, then push? or still in working?

**Comment by BaseMax** [comment]
Awesome. parseSimilar )

**Comment by BaseMax** [comment]
Thank you Izzy.

**Comment by IzzySoft** [comment]
Want "other apps by author" (`parseOthers($packageName)`) as well, if available?

What I'm a bit unsure about: on those methods returning a list, which approach do you prefer on failure:

* returning `[success:0, message:reason]` instead (and if so, include `success:1` with a "good result?
* simply returning an empty array, and have a `getLastError()` method for obtaining the reason?

For lists, the latter would make parsing easier (and you can ask "Why???" on `empty(result)`. Would probably be good if we handle that the same way consistently – where distinguishing between "details on X" (parseApplication, parsePerms) and "list of X" would IMHO be OK.

**Pull request merged**
