### PR TITLE
add debug method (dump_raw) to dump internal data / page structures

### PR DESCRIPTION
**Pull request by IzzySoft**
This PR adds a new method `dump_raw()` allowing to dump the resources:

* the full source retrieved from Google servers
* one JSON file per embedded data source

Seemed helpful to me when debugging things or looking at how to add new features (without placing all kinds of print commands into the class file every time :wink:)

### CODE REVIEW

**Comment by IzzySoft** [comment]
OK, ds:2 (never encountered with data yet) & ds:4 (icon, featureGraphic, video.txt) seem often to be empty, all others should be dumped now:

* ds:0 categories of this app
* ds:1 account links (library, payments, my play activity, offers, settings)
* ds:2 (not yet encountered, so no idea)
* ds:3 links to the app in other languages (i.e. the base link with `?hl=XX&gl=ZZ` appended)
* ds:4 featureGraphic, video (often missing on 1st call)
* ds:5 age rating (PG) etc
* ds:6 developer data? other apps etc.
* ds:7 Reviews
* ds:8 Google TOS?
* ds:9 ? Play Pass, Play Points, Gift cards, Refund policy, Parent Guide, Family Sharing …

ds:1, ds:8 & ds:9 seem to be identical for (most|all|many) apps (naturally).

**Comment by IzzySoft** [comment]
@BaseMax may I kindly ask to merge, so our code bases are not getting out of sync? Or are you opposed to merging it?

**Comment by BaseMax** [comment]
Hi Izzy, sorry for the delay. It seems I missed your updates here. And thanks for recalling it for me.
Merged.
Best

**Comment by IzzySoft** [comment]
Hehe, happens. Thanks for the merge!

**Pull request merged**
