### PR TITLE
add method parsePrivacy() to obtain Data Safety details for a given app

### PR DESCRIPTION
**Pull request by IzzySoft**
New functionality to be added once 1.0.1 has been tagged – and this new method has been tested by at least one other person :wink:

This is about the new "Data Safety" details Google added after Apple started this in their AppStore. To find a candidate with details: `https://play.google.com/store/apps/datasafety?id=com.grupet.web.app&hl=en` – which is what the results in the following spoiler are from.

<details><summary>example result</summary><pre><code>Array
(
    [success] => 1
    [values] => Array
        (
            [0] => Array
                (
                    [name] => No data shared with third parties
                    [desc] => The developer says this app doesn't share user data with other companies or organizations. 
                    [extras] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [name] => Data collected
                    [desc] => Data this app may collect
                    [extras] => Array
                        (
                            [0] => Array
                                (
                                    [name] => Messages
                                    [desc] => Other in-app messages
                                )

                            [1] => Array
                                (
                                    [name] => Device or other IDs
                                    [desc] => Device or other IDs
                                )

                        )

                )

            [2] => Array
                (
                    [name] => Security practices
                    [desc] => see extras
                    [extras] => Array
                        (
                            [0] => Array
                                (
                                    [name] => Data is encrypted in transit
                                    [desc] => Your data is transferred over a secure connection
                                )

                            [1] => Array
                                (
                                    [name] => You can request that data be deleted
                                    [desc] => The developer provides a way for you to request that your data be deleted
                                )

                        )

                )

        )

    [message] => 
)</code></pre></details>

Once this is merged and I find some more time, I might also add something like `parseReviews()`. Not sure if I can find a separate URL to pull those from, but they are part of the page having the app details and could be captured there…

### CODE REVIEW

**Comment by BaseMax** [comment]
Hi Izzy, Thanks for your work.
It's good to add `parsePrivacy`.

**Comment by IzzySoft** [comment]
Thanks for merging! I just updated the README then as well (should have been done with this PR but I didn't remember in time :see_no_evil:)

**Comment by BaseMax** [comment]
Good to have that in README too.

Izzy, What's your full name?

**Comment by IzzySoft** [comment]
> Izzy, What's your full name?

"Izzy" is the nick I'm going by for, ugh, about 30 years at least, it's derived from my "middle name" (which I favor over my first as it describes me more precisely: "Andreas" is fine, coming from the Greek [ανδρείος](https://www.wordhippo.com/what-is/the-meaning-of/greek-word-98021f27a5ec87124e20756000fe59f63086ae3e.html) – but I don't think I'm really "gallant" or "doughty". "Itzchak" however is describing me quite well: laughing (or "making others laugh", depending on what Grammar you put in) is part of my nature :smile:)

Going via my Github profile page and following the homepage URL, then select the [Imprint](https://android.izzysoft.de/impressum.php) tab for any details needed – err, now you just need to tap/click that link :rofl: And if you select the "Applist" tab, you see where some of the details obtained by GooglePlayWebServiceAPI go to. Others are used for what's in the App-Repo (when initializing a new app which is also listed at Play), better represented [here](https://apt.izzysoft.de/fdroid).

Why I mention all this instead of just posting my name? In case you want some references on where it's used. Take your pick if you like (and I'm not "sour" if you don't – I'm just giving options :wink:).

**Pull request merged**
